app/routes/post.py
from flask import Blueprint, render_template, request , redirect , flash , abort, url_for
from flask_login import login_required, current_user
from ..extensions import db
from ..models.user import User
from ..forms import StudentForm, TeacherForm
from ..models.post import Post

post = Blueprint('post', __name__)



@post.route('/', methods=['POST','GET'])
def all():
    form = TeacherForm()
    form.teacher.choices = ['Выберите преподавателя']
    for t in User.query.filter_by(status='teacher'):
        form.teacher.choices.append(t.name)
    if request.method=="POST":
        teacher = request.form['teacher']
        if teacher == "Выберите преподавателя":
            flash('Выберите преподавателя!', 'error')
            return redirect('/')
        else:
            teacher_id = User.query.filter_by(name=teacher).first().id
            posts = Post.query.filter_by(teacher=teacher_id).order_by(Post.date.desc()).all()
    else:
        posts = Post.query.order_by(Post.date.desc()).limit(20).all()
    return render_template('post/all.html', posts=posts, user=User, form=form)


@post.route('/post/create', methods=['POST','GET'])
@login_required
def create():
    form = StudentForm()
    form.student.choices = [s.name for s in User.query.filter_by(status='student')]
    if request.method == 'POST':
        postname= request.form.get('postname')
        student = request.form.get('student')  

        student_id = User.query.filter_by(name = student).first().id

        post = Post(teacher = current_user.id, postname = postname , student = student_id)
        
        try:
            db.session.add(post)
            db.session.commit()
            flash(f"Пост номер {post.id_post} успешно создан!", "success")
            return redirect('/') 
        except Exception as e:
            print(str(e))
    else:
        return render_template('post/create.html', form = form)


@post.route('/post/<int:id>/update', methods=['POST','GET'])
@login_required
def update(id):
    post = Post.query.get(id)

    if post.author.id == current_user.id:
        form = StudentForm()
        form.student.data = User.query.filter_by(id=post.student).first().name
        form.student.choices = [s.name for s in User.query.filter_by(status='user')]
        if request.method == 'POST':
            post.postname= request.form.get('postname')
            student = request.form.get('student')   
            post.student = User.query.filter_by(name = student).first().id
            try:
                db.session.commit()
                return redirect('/')
            except Exception as e:
                print(str(e))

        else:
            return render_template('post/update.html', post=post, form = form)
    else:
        abort(403)
    
@post.route('/post/<int:id>/delete', methods=['POST','GET'])
@login_required
def delete(id):
    post = Post.query.get(id)
    if post.author.id == current_user.id:
        try:
            db.session.delete(post)
            db.session.commit()
            return redirect('/')
        except Exception as e:
            print(str(e))
            return str(e)
    else:
        abort(403)

app/routes/schedule.py
from flask import Blueprint, render_template, request, redirect, flash, abort, current_app, url_for, jsonify
from ..functions import generate_group_schedule_url
from ..parser import parsing
from flask_login import current_user, login_required
import requests
import os
import datetime
import json



schedule = Blueprint('schedule', __name__)

@schedule.route('/schedule')
@schedule.route('/schedule/<group_id>', methods=['POST', 'GET'])
@login_required  # Добавьте эту декорацию если нужно
def all(group_id=None):
    if group_id is None:
        if current_user.is_authenticated:
            group_id = current_user.group
        else:
             return redirect(url_for('user.login'))
    
    group = generate_group_schedule_url(str(group_id))
    response = requests.get(group)
    
    if response.status_code != 200:
        flash('Ошибка загрузки расписания', 'error')
        return redirect(url_for('post.all'))
    
    response_data = response.json()
    first_item = response_data['data'][0] 
    file_link = first_item.get('iCalLink')
    response2 = requests.get(file_link, timeout=30)
    
    filename = f"schedule_{group_id}.ics"
    filepath = os.path.join("app/static/json", filename)
    
    with open(filepath, 'wb') as f:
        f.write(response2.content)
    
    ics_path = filepath
    parsing(ics_path, group_id)
    
    return render_template('/schedule/schedule.html', group_number=group_id)

@schedule.route('/api/schedule/<group_id>', methods=['POST', 'GET'])
def get_schedule_perday(group_id):
    first_september = 244   
    counter_day_of_year = int(datetime.datetime.now().strftime("%j"))
    counter_week = (counter_day_of_year - first_september) // 7
    day_name = datetime.datetime.now().strftime("%A") 
    filepath = f"app/static/json/schedule_data_{group_id}.json"
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
        week_schedule = data[counter_week]
        day_schedule = week_schedule.get(day_name)
        return jsonify(day_schedule)

app/routes/user.py
from flask import Blueprint,render_template,redirect, flash , url_for , request 
from ..extensions import db , bcrypt
from ..models.user import User
from ..forms import RegistrationForm, LoginForm, AuthForm
from ..functions import save_picture
from flask_login import login_user, logout_user , current_user
user = Blueprint('user', __name__)

@user.route('/user/register', methods=['POST','GET'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        try:
            avatar_filename = save_picture(form.avatar.data)
        except Exception as e:
            flash(f"Выберите фото!", "danger")
            return redirect(url_for('user.register'))
        user = User(name = form.name.data, login = form.login.data, avatar = avatar_filename,group = form.group.data, password = hashed_password, status = form.status.data)
        if user.status == "default":
            flash(f"Выберите правильную должность!", "danger")
            redirect(url_for('user.register'))
        else:    
            try:
                db.session.add(user)
                db.session.commit()
                flash(f"Вы успешно зарегестрировались, {form.login.data} !", "success")
                return redirect(url_for('user.login')) #todo: если не добавил файл - вылезает ошибка
            except Exception as e:
                print(str(e))
                flash(f"При регистрации произошла ошибка!", "danger")
    return render_template('user/register.html', form=form)

@user.route('/user/login', methods=['POST','GET'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(login = form.login.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember = form.remember.data)
            next_page = request.args.get('next')
            flash(f"Вы успешно авторизованы, {form.login.data} !", "success")
            return redirect(next_page) if next_page else redirect(url_for('post.all'))
        else:
            flash(f"Ошибка входа. Проверьте логин или пароль", "danger")
    return render_template('user/login.html', form=form)

@user.route('/user/logout', methods=['POST','GET'])
def logout():
    logout_user()
    return redirect(url_for('post.all'))

@user.route('/user/info', methods=['POST','GET'])
def info():
    return render_template('user/info.html')

@user.route('/tgauth', methods=['POST','GET'])
def auth():
    form = AuthForm()
    if form.validate_on_submit():
        tg = form.tg_id.data
        id_user = current_user.id
        user = User.query.get(id_user)
        if user:
            user.tgid = tg
            db.session.commit()
            flash(f"Вы успешно привязали тг, {current_user.login} !", "success")
        else:
            flash(f"Ошибка привязки", "danger")
    return render_template('user/auth.html', form=form)

app/templates/main/_flash.html
<!-- Flash -->
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{message}}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}
<!-- Flash -->

app/templates/main/_footer.html
<footer class="py-3 my-4 text-bg-dark">
  <div class="container">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item">
          <a href="{{url_for('post.all')}}" class="nav-link px-2 text-white">Лента</a>
        </li>
        <li class="nav-item">
          {% if current_user.is_authenticated %}
            <a href="{{ url_for('schedule.all', group_id=current_user.group) }}" class="nav-link px-2 text-white">Расписание</a>
          {% else %}
            <a href="{{ url_for('user.login') }}" class="nav-link px-2 text-white">Расписание</a>
          {% endif %}
        </li>
        <li class="nav-item">
          <a href="https://rahmedovdamir.ru/" class="nav-link px-2 text-white">Портфолио</a>
        </li>
      </ul>
      <p class="text-center text-white">© Damir Rahmedov</p>
  </div>
</footer>

app/templates/main/_header.html
<header class="p-3 text-bg-dark">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="{{url_for('post.all')}}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <img class="header_image" src="{{url_for('static',filename='img/favicon.ico')}}">
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{{url_for('post.all')}}" class="nav-link px-2 text-white">Лента</a></li>
        {% if current_user.is_authenticated and current_user.status == 'teacher' %}
          <li><a href="{{ url_for('post.create') }}" class="nav-link px-2 text-white">Добавить пост</a></li>
        {% endif %}
        <li>
          {% if current_user.is_authenticated %}
            <a href="{{ url_for('schedule.all', group_id=current_user.group) }}" class="nav-link px-2 text-white">Расписание</a>
          {% else %}
            <a href="{{ url_for('user.login') }}" class="nav-link px-2 text-white">Расписание</a>
          {% endif %}
        </li>
        <li>
          {% if current_user.is_authenticated %}
            <a href="{{ url_for('user.auth') }}" class="nav-link px-2 text-white">Привязка Telegram</a>
          {% endif %}
        </li>
      </ul>

      <div class="text-end">
        {% if current_user.is_authenticated %}
          <a href="{{url_for('user.info')}}" class="btn btn-outline-light me-2">{{current_user.login}}</a>
          <a href="{{url_for('user.logout')}}" class="btn btn-outline-light me-2">Выйти</a>
        {% else %}
          <a href="{{url_for('user.login')}}" class="btn btn-outline-light me-2">Войти</a>
          <a href="{{url_for('user.register')}}" class="btn btn-warning">Регистрация</a>
        {% endif %}
      </div> 
    </div>
  </div>
</header>

app/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/x-icon" href="{{url_for('static', filename = 'img/favicon.ico')}}">
    <link rel="stylesheet" href="{{url_for('static', filename = 'css/libs/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename = 'css/main.css')}}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block style %}  {% endblock %}
    <title>{% block title %} {% endblock %}</title>
</head>

<body>
<div class="page">
    <header class="header"> {% include 'main/_header.html' %}  </header>
    <main class="content"> 
        {% include 'main/_flash.html' %}
        <h1>{{ self.title() }}</h1>
        {% block content %} {% endblock %} 
    </main>
    <footer>{% include 'main/_footer.html' %}</footer>
</div>

    
    <script src="{{url_for('static', filename='js/libs/bootstrap.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/app.js')}}"></script>
</body>
</html>