app/models/post.py
from datetime import datetime
from ..extensions import db

class Post(db.Model):
    id_post = db.Column(db.Integer, primary_key=True)
    postname = db.Column(db.String(50))
    teacher  = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'))
    student  = db.Column(db.Integer)
    date = db.Column(db.DateTime, default = datetime.utcnow)

app/routes/post.py
from flask import Blueprint, render_template, request , redirect , flash , abort, url_for
from flask_login import login_required, current_user
from ..extensions import db
from ..models.user import User
from ..forms import StudentForm, TeacherForm
from ..models.post import Post

post = Blueprint('post', __name__)



@post.route('/', methods=['POST','GET'])
def all():
    form = TeacherForm()
    form.teacher.choices = ['Выберите преподавателя']
    for t in User.query.filter_by(status='teacher'):
        form.teacher.choices.append(t.name)
    if request.method=="POST":
        teacher = request.form['teacher']
        if teacher == "Выберите преподавателя":
            flash('Выберите преподавателя!', 'error')
            return redirect('/')
        else:
            teacher_id = User.query.filter_by(name=teacher).first().id
            posts = Post.query.filter_by(teacher=teacher_id).order_by(Post.date.desc()).all()
    else:
        posts = Post.query.order_by(Post.date.desc()).limit(20).all()
    return render_template('post/all.html', posts=posts, user=User, form=form)


@post.route('/post/create', methods=['POST','GET'])
@login_required
def create():
    form = StudentForm()
    form.student.choices = [s.name for s in User.query.filter_by(status='student')]
    if request.method == 'POST':
        postname= request.form.get('postname')
        student = request.form.get('student')  

        student_id = User.query.filter_by(name = student).first().id

        post = Post(teacher = current_user.id, postname = postname , student = student_id)
        
        try:
            db.session.add(post)
            db.session.commit()
            flash(f"Пост номер {post.id_post} успешно создан!", "success")
            return redirect('/') 
        except Exception as e:
            print(str(e))
    else:
        return render_template('post/create.html', form = form)


@post.route('/post/<int:id>/update', methods=['POST','GET'])
@login_required
def update(id):
    post = Post.query.get(id)

    if post.author.id == current_user.id:
        form = StudentForm()
        form.student.data = User.query.filter_by(id=post.student).first().name
        form.student.choices = [s.name for s in User.query.filter_by(status='user')]
        if request.method == 'POST':
            post.postname= request.form.get('postname')
            student = request.form.get('student')   
            post.student = User.query.filter_by(name = student).first().id
            try:
                db.session.commit()
                return redirect('/')
            except Exception as e:
                print(str(e))

        else:
            return render_template('post/update.html', post=post, form = form)
    else:
        abort(403)
    
@post.route('/post/<int:id>/delete', methods=['POST','GET'])
@login_required
def delete(id):
    post = Post.query.get(id)
    if post.author.id == current_user.id:
        try:
            db.session.delete(post)
            db.session.commit()
            return redirect('/')
        except Exception as e:
            print(str(e))
            return str(e)
    else:
        abort(403)

app/templates/post/all.html
{% extends 'main/base.html' %}

{% block title %} {% endblock %}

{% block style %}  
    <link rel="stylesheet" href="{{url_for('static', filename='css/blocks/table.css')}}"> 
    <link rel="stylesheet" href="{{url_for('static', filename='css/libs/font-awesome.min.css')}}"> 
{% endblock %}




{% block content %}
<form method="post" class="form-control d-flex flex-row gap-2" id="teacherForm">
    {{form.csrf_token}}
    {{form.teacher}}
    <input type="submit" class="btn btn-success" value="Показать">
</form>

<div class = "table-responsive custom-table-responsive">
    <table class="table custom-table">
        <thead>
            <tr>
                <th scope="col">Преподаватель</th>
                <th scope="col">Пост</th>
                <th scope="col">Студент</th>
                <th scope="col">Действия</th>  
            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
            <tr scope="row">
                <td>
                    <img width="96px" height="96px" src="{{url_for('static',filename='upload/'+post.author.avatar)}}" alt="Автор">
                    {{ post.author.name }}
                </td>
                <td>{{ post.postname }}</td>
                
                <td>
                    {% with student = user.query.get(post.student) %}
                        <img width="96px" height="96px" src="{{url_for('static',filename='upload/'+student.avatar)}}" alt="Студент">
                        {{student.name}}
                    {% endwith %}

                </td> 
                <td>
                    {% if current_user.is_authenticated and post.author.id == current_user.id %}
                    <a href="{{url_for('post.update', id = post.id_post)}}" class="btn btn-sm btn-secondary"><span class="fa fa-edit"></span></a>
                    <a href="{{url_for('post.delete', id = post.id_post)}}" class="btn btn-sm btn-danger"><span class="fa fa-trash"></span></a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %} 

app/templates/post/create.html
{% extends 'main/base.html' %}

{% block title %} Добавление поста {% endblock %}

{% block content %} 
<form method="post" class="form-control d-flex flex-column gap-2">
    <input name="postname" type="text"  placeholder="Содержимое поста" class="form-control">
    {{form.student}}
    <input value="Добавить" type="submit" class="btn btn-success"></inpit>
</form>
{% endblock %} 

app/templates/post/update.html
{% extends 'main/base.html' %}

{% block title %} Редактрование поста {{post.id_post}} {% endblock %}

{% block content %} 
<form method="post" class="form-control d-flex flex-column gap-2">
    <input value="{{post.postname}}" name="postname" type="text"  placeholder="Название поста" class="form-control">
    {{form.student}}
    <input value="Обновить" type="submit" class="btn btn-success"></inpit>
</form>
{% endblock %} 